apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: springboot-api
spec:
  type: openapi
  lifecycle: production
  owner: group:dev-team
  definition:
    $text: https://raw.githubusercontent.com/karimshaik-cmd/Springboot-CI-CD-Pipeline/main/openapi.yaml
