apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-pipeline
  description: Spring Boot CI/CD pipeline with Jenkins
  annotations:
    github.com/project-slug: karimshaik-cmd/Springboot-CI-CD-Pipeline
    backstage.io/techdocs-ref: dir:.
  tags:
      - spring boot
  links: 
      - url: http://localhost:8080/home
      - title: Dashboard
      - icon: Dashboard
      - type: Dashboard
spec:
  type: service
  lifecycle: production
  owner: user:karimshaik-cmd
