---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: springboot-api-location
spec:
  type: url
  targets:
    - https://github.com/karimshaik-cmd/Springboot-CI-CD-Pipeline/blob/main/api.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-pipeline
  description: Spring Boot CI/CD pipeline with Jenkins
  annotations:
    github.com/project-slug: karimshaik-cmd/Springboot-CI-CD-Pipeline
    backstage.io/techdocs-ref: dir:.
  tags:
    - spring-boot
  links:
    - url: https://github.com/karimshaik-cmd
      title: GitHub Profile
      icon: github

    - url: http://localhost:9090/job/springboot-pipeline/
      title: Jenkins Pipeline
      icon: dashboard

spec:
  type: service
  lifecycle: production
  owner: group:dev-team
  providesApis:
    - springboot-api
